:sparkles: added cloud link
kagonlineteam/KAG-APP pull request #158
Opened 2022-04-05 17:05 UTC by RobinArlinghaus

**Close #134**

### Typ
Was für eine Art von Veränderungen wird hier vorgenommen?
_Lösche die nicht zutreffenden_

- Nutzer/innen die cloudConsent haben wird ein link zur Cloud angezeigt

### Implementation
Welche Ideen gab es zur Implementation? Was galt es zu verbessern? _Bitte möglichst detailliert die Implementation erklären_

### Checklist

_Alle erfüllten Boxen ankreuzen. Diese Liste kann auch nach Erstellung der Pull Request vervollständigt werden. Unter diesen Gesichtspunkten wird die Implementation begutachtet._

- [x] Ich habe die Tests erweitert um zu zeigen, dass der Bugfix/das Feature funktioniert
- [x] Der neue Code hält sich an die Coding Standards
- [x] Im Code befinden sich wichtige Kommentare, falls angemessen

2022-04-23 21:36 UTC, Phantom061 requested changes
Issue nummer eintragen

2022-04-30 11:10 UTC, strifel submitted a review, later dismissed
Sorry für das viel zu späte review

2022-04-30 11:11 UTC, strifel commented
@Phantom061 bitte mergen

2022-05-19 15:19 UTC, Phantom061 submitted a review, later dismissed
Ist toll

2022-05-20 07:05 UTC, strifel approved these changes

2022-05-20 07:16 UTC, merged