:fire: remove animation code an set a fixed width for every Feriencountdown element
kagonlineteam/KAG-APP pull request #166
Opened 2022-05-19 15:18 UTC by Phantom061

**Close #165**

### Typ
Was für eine Art von Veränderungen wird hier vorgenommen?
_Lösche die nicht zutreffenden_

- Bugfix

### Implementation
Welche Ideen gab es zur Implementation? Was galt es zu verbessern? _Bitte möglichst detailliert die Implementation erklären_

### Checklist

_Alle erfüllten Boxen ankreuzen. Diese Liste kann auch nach Erstellung der Pull Request vervollständigt werden. Unter diesen Gesichtspunkten wird die Implementation begutachtet._

- [x] Ich habe die Tests erweitert um zu zeigen, dass der Bugfix/das Feature funktioniert
- [x] Der neue Code hält sich an die Coding Standards
- [x] Im Code befinden sich wichtige Kommentare, falls angemessen

2022-05-19 15:52 UTC, themathman2 commented
Wenn das als Linux-App vorliegt, teste ich gerne.

2022-05-19 15:53 UTC, themathman2 commented
oder mir noch einmal einer verrät, wie ich das Testbild finde.

2022-05-19 15:54 UTC, strifel requested changes
Bitte imports entfernen und das flip Package aus der pubspec (und lock) entfernen

2022-05-20 18:05 UTC, strifel commented
jetzt noch die restlichen unnötigen Imports die der linter bemekert

2022-06-02 12:58 UTC, strifel approved these changes

2022-06-03 07:52 UTC, merged