:sparkles: add Homework function
kagonlineteam/KAG-APP pull request #177
Opened 2022-08-03 20:58 UTC by Phantom061

**Close #163**

### Typ
Was für eine Art von Veränderungen wird hier vorgenommen?
_Lösche die nicht zutreffenden_

- Neues Feature / Erweiterung eines Features

### Implementation
Welche Ideen gab es zur Implementation? Was galt es zu verbessern? _Bitte möglichst detailliert die Implementation erklären_

### Checklist

_Alle erfüllten Boxen ankreuzen. Diese Liste kann auch nach Erstellung der Pull Request vervollständigt werden. Unter diesen Gesichtspunkten wird die Implementation begutachtet._

- [ ] Ich habe die Tests erweitert um zu zeigen, dass der Bugfix/das Feature funktioniert
- [x] Der neue Code hält sich an die Coding Standards
- [x] Im Code befinden sich wichtige Kommentare, falls angemessen

2022-08-04 00:34 UTC, strifel requested changes

2022-08-04 00:34 UTC, strifel commented on lib/api/api.dart
> +      }
Kann durch einen map Aufruf ersetzt werden

2022-08-04 00:35 UTC, strifel commented
Muss mir morgen das API Implementierungs zeugs nochmal genau angucken und alles testen.

Bitte mich nochmal erinnern falls ich es vergesse

2022-08-04 13:35 UTC, strifel commented
Am Handy ist die Liste unten jetzt sehr voll und man kann nicht mehr jeden Text lesen

2022-08-07 10:53 UTC, Phantom061 commented on lib/components/homework.dart
> +  _datePicker(BuildContext context, initialDeadline) {
Habe ich überlegt, aber so wie ich das gecoded habe gehts nicht

2022-08-07 10:53 UTC, Phantom061 commented on lib/components/homework.dart
> +  _datePicker(BuildContext context, initialDeadline) {
Also wenn man nicht nochmal alles neu schreiben möchte gehts nicht

2022-08-07 13:14 UTC, strifel commented on lib/components/homework.dart
> +  _datePicker(BuildContext context, initialDeadline) {
Warum? Es gibt Methoden außerhalb von Klassen

2022-08-07 15:48 UTC, strifel requested changes

2022-08-07 15:48 UTC, strifel commented on lib/Views/Views.dart
> +        if (!API.of(KAGAppState.app.context).requests.getUserInfo().useSie && !API.of(KAGAppState.app.context).requests.getUserInfo().isOberstufe) new Homework.HomeworkView(),
Während ich einen eigenen Typ schöner fände verstehe ich, dass das kacke ist.
Dann sollten wir ein Issue machen Webmail auch umzustellen.

Lass und aber auf eine eigene Befugnis für Hausaufgaben umstellen. Dann können wir wenn irgendwas sehr kaputt ist die auch einfach entziehen.
Ich kümmere mich darum, dass alle Unter/Mittelsus die kriegen.
Würde vorschlagen `homework_use` (falls ABT microservice auch mit _ nutzt sonst halt was auch immer dazwischen ist)

2022-08-07 17:03 UTC, merged